Add first version of a User Guide
wmde/wikidata-mismatch-finder pull request #13
Opened 2021-07-08 11:58 UTC by Silvan-WMDE

For now, this includes three sections about authentication and authorization. To be expanded.

2021-07-12 13:17 UTC, itamargiv requested changes
:sunglasses: Looks fantastic, thank you for adding this. I've made a couple of editing comments, In addition to the comment I made in [#12](https://github.com/wmde/wikidata-mismatch-finder/pull/12/files#r667892253). Other than that, we are good to go!

2021-07-12 13:17 UTC, itamargiv commented on docs/UserGuide.md
> +- [Accessing the API <a id="apiAccess"></a>](#accessing-the-api-a-idapiaccessa)
I'm pretty sure these `<a>` tags aren't supposed to be here. We also need to make sure that the `#` link is correct. See suggestion.

```suggestion
- [Logging in](#login)
- [Obtaining an API token](#apiToken)
- [Accessing the API](#apiAccess)
```

2021-07-12 13:17 UTC, itamargiv commented on docs/UserGuide.md
> +You can log in to the Mismatch Finder website using your MediaWiki account on `www.wikidata.org`. Simply click the Login button on the Welcome page and get redirected to Wikidata, to allow Mismatch F
Nice and concise! Very well put, thank you!

2021-07-12 13:17 UTC, itamargiv commented on docs/UserGuide.md
> +Once you have logged in and have started to use the Mismatch Finder web interface, you may want to get access to the REST API, as well. You will need a personalised token for that, which you must pro
I think this section could benefit from a step by step (numbered list) breakdown on how to (currently) generate a token. We can update this as we progress along with the GUI development.

2021-07-12 13:17 UTC, itamargiv commented on docs/UserGuide.md
> +To access the API, include your personalised API token as `Bearer <token>` string in the `Authorization:` header field.
This repeats what was said before, but I do believe this deserves its own section. Therefore, I think this section belongs before the former section, and its content should be the first two sentences of the former section, that is:

> Once you have logged in and have started to use the Mismatch Finder web interface, you may want to get access to the REST API, as well. You will need a personalised token for that, which you must provide in the `Authorization:` header of your API requests.

2021-07-13 08:11 UTC, guergana commented on docs/UserGuide.md
> +3. **Important!** Write the created token down in a safe place, as it will not be displayed again.
Ah yes. This is good to point out!!!

2021-07-13 08:15 UTC, guergana approved these changes
Looks great for a start. :)

2021-07-13 08:21 UTC, merged