Allow users to disable confirmation dialog
wmde/wikidata-mismatch-finder pull request #181
Opened 2021-10-29 16:52 UTC by itamargiv

_**Note:** This PR depends on #178_

This change allows the user to disable the confirmation dialog that appear when submitting decisions, and persists that state into the browser's local storage.

Additionally, some convenience methods were added to the results page testing object to apply and submit review decisions more easily within the browser tests.

Bug: [T290953](https://phabricator.wikimedia.org/T290953)

2021-11-01 08:07 UTC, guergana requested changes
This is only working if I check the box and then reload the page. If I chose an option from the dropdown and the box opens and then proceed. And then I chose another option without reloading the page, the box appears again. I think this is due to the fact that you are only retrieving the value of the disableConfirmation in mounted and not saving it as a local data variable as well.

2021-11-01 16:43 UTC, itamargiv commented
> This is only working if I check the box and then reload the page. If I chose an option from the dropdown and the box opens and then proceed. And then I chose another option without reloading the page, the box appears again. I think this is due to the fact that you are only retrieving the value of the disableConfirmation in mounted and not saving it as a local data variable as well.

Thanks! It turned out that we just needed to ensure that the checkbox rest when the dialog is dismissed (rather than on every close, like before). I also made sure to fix the tests do that they would fail  in this case, as they should have.

2021-11-02 15:51 UTC, Silvan-WMDE approved these changes
Works locally, great work again - thank you! :tada:

2021-11-02 16:38 UTC, guergana approved these changes
beautiful

2021-11-02 16:45 UTC, merged